name: Download

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Update And Install Dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install wget tar aria2
      - name: Download
        run: |
          cd $HOME
          mkdir Project
          cd /home/runner/Project
          #!/bin/bash
          mdl () {
          url=$(curl -Lqs "$1"|grep "href.*download.*media.*"|tail -1|cut -d '"' -f 2)
          aria2c -x 6 "$url" # or wget "$url" if you prefer.
          }
          mdl "http://www.mediafire.com/?8gnvzhea6oj5tru" 
      - name: Compress File
        run: |
          cd /home/runner/Project
          tar vcf Download.tar *
          xz -ve Download.tar
      - name: Check Compressed File Checksum
        run: |
          cd /home/runner/Project
          echo SHA-256
          sha256sum Download.tar.xz
          echo "-------------------------------------------------------------------------------"
          echo MD5
          md5sum Download.tar.xz
      - name: Upload Downloaded File
        uses: actions/upload-artifact@v2
        with:
          name: Download.tar.xz
          path: '/home/runner/Project/Download.tar.xz'
