name: Download

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Download:
    name: Download
    runs-on: ubuntu-latest
    steps:
      - name: Update And Install Dependencies
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install aria2
      - name: Download
        run: |
          download() {
            aria2c -x16 -s1024 -o download.zip http://web.archive.org/web/20200425084614if_/https://dlcdnets.asus.com/pub/ASUS/ZenFone/ZA550KL/UL-ASUS_X00R-WW-AOSP-17.07.2003.405-user.zip || download
          }
      - name: Check Compressed File Checksum
        run: |
          echo SHA-256
          sha256sum download.zip
          echo "-------------------------------------------------------------------------------"
          echo MD5
          md5sum download.zip
      - name: Upload Downloaded File
        uses: actions/upload-artifact@v4
        with:
          name: download.zip
          path: download.zip
